/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOfflineRouteImport } from './routes/app.offline'
import { Route as OnboardingSplashRouteImport } from './routes/onboarding.splash'
import { Route as OnboardingWalletCreationRouteImport } from './routes/onboarding.wallet-creation'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as AppMarketIndexRouteImport } from './routes/app.market.index'
import { Route as AppMarketPortfolioRouteImport } from './routes/app.market.portfolio'
import { Route as AppProfileIndexRouteImport } from './routes/app.profile.index'
import { Route as AppProfileEditRouteImport } from './routes/app.profile.edit'
import { Route as AppProfileHelpRouteImport } from './routes/app.profile.help'
import { Route as AppProfileLanguageRouteImport } from './routes/app.profile.language'
import { Route as AppProfileLegalRouteImport } from './routes/app.profile.legal'
import { Route as AppProfileLogoutRouteImport } from './routes/app.profile.logout'
import { Route as AppProfileNotificationsRouteImport } from './routes/app.profile.notifications'
import { Route as AppProfilePaymentMethodsRouteImport } from './routes/app.profile.payment-methods'
import { Route as AppProfileReferRouteImport } from './routes/app.profile.refer'
import { Route as AppWalletIndexRouteImport } from './routes/app.wallet.index'
import { Route as AppWalletReceiveRouteImport } from './routes/app.wallet.receive'
import { Route as AppWalletSecurityRouteImport } from './routes/app.wallet.security'
import { Route as AppWalletSendRouteImport } from './routes/app.wallet.send'
import { Route as OnboardingIntroStepRouteImport } from './routes/onboarding.intro.$step'
import { Route as AppMarketFinancingDepositRouteImport } from './routes/app.market.financing.deposit'
import { Route as AppMarketFinancingEligibilityRouteImport } from './routes/app.market.financing.eligibility'
import { Route as AppMarketFinancingPlanRouteImport } from './routes/app.market.financing.plan'
import { Route as AppMarketFinancingRepayRouteImport } from './routes/app.market.financing.repay'
import { Route as AppMarketFinancingReviewRouteImport } from './routes/app.market.financing.review'
import { Route as AppMarketFinancingSuccessRouteImport } from './routes/app.market.financing.success'
import { Route as AppMarketInvestIdRouteImport } from './routes/app.market.invest.$id'
import { Route as AppMarketInvestAmountRouteImport } from './routes/app.market.invest.amount'
import { Route as AppMarketInvestConfirmRouteImport } from './routes/app.market.invest.confirm'
import { Route as AppMarketInvestSuccessRouteImport } from './routes/app.market.invest.success'
import { Route as AppMarketProductIdRouteImport } from './routes/app.market.product.$id'
import { Route as AppWalletTopupAmountRouteImport } from './routes/app.wallet.topup.amount'
import { Route as AppWalletTopupMethodRouteImport } from './routes/app.wallet.topup.method'
import { Route as AppWalletTopupProcessingRouteImport } from './routes/app.wallet.topup.processing'
import { Route as AppWalletTopupSuccessRouteImport } from './routes/app.wallet.topup.success'
import { Route as AppWalletTxIndexRouteImport } from './routes/app.wallet.tx.index'
import { Route as AppWalletTxIdRouteImport } from './routes/app.wallet.tx.$id'
import { Route as AppWalletWithdrawAmountRouteImport } from './routes/app.wallet.withdraw.amount'
import { Route as AppWalletWithdrawMethodRouteImport } from './routes/app.wallet.withdraw.method'
import { Route as AppWalletWithdrawSuccessRouteImport } from './routes/app.wallet.withdraw.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOfflineRoute = AppOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingSplashRoute = OnboardingSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWalletCreationRoute =
  OnboardingWalletCreationRouteImport.update({
    id: '/wallet-creation',
    path: '/wallet-creation',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppMarketIndexRoute = AppMarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketPortfolioRoute = AppMarketPortfolioRouteImport.update({
  id: '/market/portfolio',
  path: '/market/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileHelpRoute = AppProfileHelpRouteImport.update({
  id: '/profile/help',
  path: '/profile/help',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileLanguageRoute = AppProfileLanguageRouteImport.update({
  id: '/profile/language',
  path: '/profile/language',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileLegalRoute = AppProfileLegalRouteImport.update({
  id: '/profile/legal',
  path: '/profile/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileLogoutRoute = AppProfileLogoutRouteImport.update({
  id: '/profile/logout',
  path: '/profile/logout',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileNotificationsRoute = AppProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilePaymentMethodsRoute =
  AppProfilePaymentMethodsRouteImport.update({
    id: '/profile/payment-methods',
    path: '/profile/payment-methods',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfileReferRoute = AppProfileReferRouteImport.update({
  id: '/profile/refer',
  path: '/profile/refer',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletReceiveRoute = AppWalletReceiveRouteImport.update({
  id: '/wallet/receive',
  path: '/wallet/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletSecurityRoute = AppWalletSecurityRouteImport.update({
  id: '/wallet/security',
  path: '/wallet/security',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletSendRoute = AppWalletSendRouteImport.update({
  id: '/wallet/send',
  path: '/wallet/send',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingIntroStepRoute = OnboardingIntroStepRouteImport.update({
  id: '/intro/$step',
  path: '/intro/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppMarketFinancingDepositRoute =
  AppMarketFinancingDepositRouteImport.update({
    id: '/market/financing/deposit',
    path: '/market/financing/deposit',
    getParentRoute: () => AppRoute,
  } as any)
const AppMarketFinancingEligibilityRoute =
  AppMarketFinancingEligibilityRouteImport.update({
    id: '/market/financing/eligibility',
    path: '/market/financing/eligibility',
    getParentRoute: () => AppRoute,
  } as any)
const AppMarketFinancingPlanRoute = AppMarketFinancingPlanRouteImport.update({
  id: '/market/financing/plan',
  path: '/market/financing/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketFinancingRepayRoute = AppMarketFinancingRepayRouteImport.update({
  id: '/market/financing/repay',
  path: '/market/financing/repay',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketFinancingReviewRoute =
  AppMarketFinancingReviewRouteImport.update({
    id: '/market/financing/review',
    path: '/market/financing/review',
    getParentRoute: () => AppRoute,
  } as any)
const AppMarketFinancingSuccessRoute =
  AppMarketFinancingSuccessRouteImport.update({
    id: '/market/financing/success',
    path: '/market/financing/success',
    getParentRoute: () => AppRoute,
  } as any)
const AppMarketInvestIdRoute = AppMarketInvestIdRouteImport.update({
  id: '/market/invest/$id',
  path: '/market/invest/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketInvestAmountRoute = AppMarketInvestAmountRouteImport.update({
  id: '/market/invest/amount',
  path: '/market/invest/amount',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketInvestConfirmRoute = AppMarketInvestConfirmRouteImport.update({
  id: '/market/invest/confirm',
  path: '/market/invest/confirm',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketInvestSuccessRoute = AppMarketInvestSuccessRouteImport.update({
  id: '/market/invest/success',
  path: '/market/invest/success',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketProductIdRoute = AppMarketProductIdRouteImport.update({
  id: '/market/product/$id',
  path: '/market/product/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletTopupAmountRoute = AppWalletTopupAmountRouteImport.update({
  id: '/wallet/topup/amount',
  path: '/wallet/topup/amount',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletTopupMethodRoute = AppWalletTopupMethodRouteImport.update({
  id: '/wallet/topup/method',
  path: '/wallet/topup/method',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletTopupProcessingRoute =
  AppWalletTopupProcessingRouteImport.update({
    id: '/wallet/topup/processing',
    path: '/wallet/topup/processing',
    getParentRoute: () => AppRoute,
  } as any)
const AppWalletTopupSuccessRoute = AppWalletTopupSuccessRouteImport.update({
  id: '/wallet/topup/success',
  path: '/wallet/topup/success',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletTxIndexRoute = AppWalletTxIndexRouteImport.update({
  id: '/wallet/tx/',
  path: '/wallet/tx/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletTxIdRoute = AppWalletTxIdRouteImport.update({
  id: '/wallet/tx/$id',
  path: '/wallet/tx/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletWithdrawAmountRoute = AppWalletWithdrawAmountRouteImport.update({
  id: '/wallet/withdraw/amount',
  path: '/wallet/withdraw/amount',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletWithdrawMethodRoute = AppWalletWithdrawMethodRouteImport.update({
  id: '/wallet/withdraw/method',
  path: '/wallet/withdraw/method',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletWithdrawSuccessRoute =
  AppWalletWithdrawSuccessRouteImport.update({
    id: '/wallet/withdraw/success',
    path: '/wallet/withdraw/success',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offline': typeof AppOfflineRoute
  '/onboarding/splash': typeof OnboardingSplashRoute
  '/onboarding/wallet-creation': typeof OnboardingWalletCreationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/market/portfolio': typeof AppMarketPortfolioRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/help': typeof AppProfileHelpRoute
  '/app/profile/language': typeof AppProfileLanguageRoute
  '/app/profile/legal': typeof AppProfileLegalRoute
  '/app/profile/logout': typeof AppProfileLogoutRoute
  '/app/profile/notifications': typeof AppProfileNotificationsRoute
  '/app/profile/payment-methods': typeof AppProfilePaymentMethodsRoute
  '/app/profile/refer': typeof AppProfileReferRoute
  '/app/wallet/receive': typeof AppWalletReceiveRoute
  '/app/wallet/security': typeof AppWalletSecurityRoute
  '/app/wallet/send': typeof AppWalletSendRoute
  '/onboarding/intro/$step': typeof OnboardingIntroStepRoute
  '/app/market/': typeof AppMarketIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
  '/app/market/financing/deposit': typeof AppMarketFinancingDepositRoute
  '/app/market/financing/eligibility': typeof AppMarketFinancingEligibilityRoute
  '/app/market/financing/plan': typeof AppMarketFinancingPlanRoute
  '/app/market/financing/repay': typeof AppMarketFinancingRepayRoute
  '/app/market/financing/review': typeof AppMarketFinancingReviewRoute
  '/app/market/financing/success': typeof AppMarketFinancingSuccessRoute
  '/app/market/invest/$id': typeof AppMarketInvestIdRoute
  '/app/market/invest/amount': typeof AppMarketInvestAmountRoute
  '/app/market/invest/confirm': typeof AppMarketInvestConfirmRoute
  '/app/market/invest/success': typeof AppMarketInvestSuccessRoute
  '/app/market/product/$id': typeof AppMarketProductIdRoute
  '/app/wallet/topup/amount': typeof AppWalletTopupAmountRoute
  '/app/wallet/topup/method': typeof AppWalletTopupMethodRoute
  '/app/wallet/topup/processing': typeof AppWalletTopupProcessingRoute
  '/app/wallet/topup/success': typeof AppWalletTopupSuccessRoute
  '/app/wallet/tx/$id': typeof AppWalletTxIdRoute
  '/app/wallet/withdraw/amount': typeof AppWalletWithdrawAmountRoute
  '/app/wallet/withdraw/method': typeof AppWalletWithdrawMethodRoute
  '/app/wallet/withdraw/success': typeof AppWalletWithdrawSuccessRoute
  '/app/wallet/tx/': typeof AppWalletTxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offline': typeof AppOfflineRoute
  '/onboarding/splash': typeof OnboardingSplashRoute
  '/onboarding/wallet-creation': typeof OnboardingWalletCreationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app': typeof AppIndexRoute
  '/app/market/portfolio': typeof AppMarketPortfolioRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/help': typeof AppProfileHelpRoute
  '/app/profile/language': typeof AppProfileLanguageRoute
  '/app/profile/legal': typeof AppProfileLegalRoute
  '/app/profile/logout': typeof AppProfileLogoutRoute
  '/app/profile/notifications': typeof AppProfileNotificationsRoute
  '/app/profile/payment-methods': typeof AppProfilePaymentMethodsRoute
  '/app/profile/refer': typeof AppProfileReferRoute
  '/app/wallet/receive': typeof AppWalletReceiveRoute
  '/app/wallet/security': typeof AppWalletSecurityRoute
  '/app/wallet/send': typeof AppWalletSendRoute
  '/onboarding/intro/$step': typeof OnboardingIntroStepRoute
  '/app/market': typeof AppMarketIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/wallet': typeof AppWalletIndexRoute
  '/app/market/financing/deposit': typeof AppMarketFinancingDepositRoute
  '/app/market/financing/eligibility': typeof AppMarketFinancingEligibilityRoute
  '/app/market/financing/plan': typeof AppMarketFinancingPlanRoute
  '/app/market/financing/repay': typeof AppMarketFinancingRepayRoute
  '/app/market/financing/review': typeof AppMarketFinancingReviewRoute
  '/app/market/financing/success': typeof AppMarketFinancingSuccessRoute
  '/app/market/invest/$id': typeof AppMarketInvestIdRoute
  '/app/market/invest/amount': typeof AppMarketInvestAmountRoute
  '/app/market/invest/confirm': typeof AppMarketInvestConfirmRoute
  '/app/market/invest/success': typeof AppMarketInvestSuccessRoute
  '/app/market/product/$id': typeof AppMarketProductIdRoute
  '/app/wallet/topup/amount': typeof AppWalletTopupAmountRoute
  '/app/wallet/topup/method': typeof AppWalletTopupMethodRoute
  '/app/wallet/topup/processing': typeof AppWalletTopupProcessingRoute
  '/app/wallet/topup/success': typeof AppWalletTopupSuccessRoute
  '/app/wallet/tx/$id': typeof AppWalletTxIdRoute
  '/app/wallet/withdraw/amount': typeof AppWalletWithdrawAmountRoute
  '/app/wallet/withdraw/method': typeof AppWalletWithdrawMethodRoute
  '/app/wallet/withdraw/success': typeof AppWalletWithdrawSuccessRoute
  '/app/wallet/tx': typeof AppWalletTxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offline': typeof AppOfflineRoute
  '/onboarding/splash': typeof OnboardingSplashRoute
  '/onboarding/wallet-creation': typeof OnboardingWalletCreationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/market/portfolio': typeof AppMarketPortfolioRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/help': typeof AppProfileHelpRoute
  '/app/profile/language': typeof AppProfileLanguageRoute
  '/app/profile/legal': typeof AppProfileLegalRoute
  '/app/profile/logout': typeof AppProfileLogoutRoute
  '/app/profile/notifications': typeof AppProfileNotificationsRoute
  '/app/profile/payment-methods': typeof AppProfilePaymentMethodsRoute
  '/app/profile/refer': typeof AppProfileReferRoute
  '/app/wallet/receive': typeof AppWalletReceiveRoute
  '/app/wallet/security': typeof AppWalletSecurityRoute
  '/app/wallet/send': typeof AppWalletSendRoute
  '/onboarding/intro/$step': typeof OnboardingIntroStepRoute
  '/app/market/': typeof AppMarketIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
  '/app/market/financing/deposit': typeof AppMarketFinancingDepositRoute
  '/app/market/financing/eligibility': typeof AppMarketFinancingEligibilityRoute
  '/app/market/financing/plan': typeof AppMarketFinancingPlanRoute
  '/app/market/financing/repay': typeof AppMarketFinancingRepayRoute
  '/app/market/financing/review': typeof AppMarketFinancingReviewRoute
  '/app/market/financing/success': typeof AppMarketFinancingSuccessRoute
  '/app/market/invest/$id': typeof AppMarketInvestIdRoute
  '/app/market/invest/amount': typeof AppMarketInvestAmountRoute
  '/app/market/invest/confirm': typeof AppMarketInvestConfirmRoute
  '/app/market/invest/success': typeof AppMarketInvestSuccessRoute
  '/app/market/product/$id': typeof AppMarketProductIdRoute
  '/app/wallet/topup/amount': typeof AppWalletTopupAmountRoute
  '/app/wallet/topup/method': typeof AppWalletTopupMethodRoute
  '/app/wallet/topup/processing': typeof AppWalletTopupProcessingRoute
  '/app/wallet/topup/success': typeof AppWalletTopupSuccessRoute
  '/app/wallet/tx/$id': typeof AppWalletTxIdRoute
  '/app/wallet/withdraw/amount': typeof AppWalletWithdrawAmountRoute
  '/app/wallet/withdraw/method': typeof AppWalletWithdrawMethodRoute
  '/app/wallet/withdraw/success': typeof AppWalletWithdrawSuccessRoute
  '/app/wallet/tx/': typeof AppWalletTxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/admin'
    | '/app/notifications'
    | '/app/offline'
    | '/onboarding/splash'
    | '/onboarding/wallet-creation'
    | '/onboarding/welcome'
    | '/app/'
    | '/app/market/portfolio'
    | '/app/profile/edit'
    | '/app/profile/help'
    | '/app/profile/language'
    | '/app/profile/legal'
    | '/app/profile/logout'
    | '/app/profile/notifications'
    | '/app/profile/payment-methods'
    | '/app/profile/refer'
    | '/app/wallet/receive'
    | '/app/wallet/security'
    | '/app/wallet/send'
    | '/onboarding/intro/$step'
    | '/app/market/'
    | '/app/profile/'
    | '/app/wallet/'
    | '/app/market/financing/deposit'
    | '/app/market/financing/eligibility'
    | '/app/market/financing/plan'
    | '/app/market/financing/repay'
    | '/app/market/financing/review'
    | '/app/market/financing/success'
    | '/app/market/invest/$id'
    | '/app/market/invest/amount'
    | '/app/market/invest/confirm'
    | '/app/market/invest/success'
    | '/app/market/product/$id'
    | '/app/wallet/topup/amount'
    | '/app/wallet/topup/method'
    | '/app/wallet/topup/processing'
    | '/app/wallet/topup/success'
    | '/app/wallet/tx/$id'
    | '/app/wallet/withdraw/amount'
    | '/app/wallet/withdraw/method'
    | '/app/wallet/withdraw/success'
    | '/app/wallet/tx/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/admin'
    | '/app/notifications'
    | '/app/offline'
    | '/onboarding/splash'
    | '/onboarding/wallet-creation'
    | '/onboarding/welcome'
    | '/app'
    | '/app/market/portfolio'
    | '/app/profile/edit'
    | '/app/profile/help'
    | '/app/profile/language'
    | '/app/profile/legal'
    | '/app/profile/logout'
    | '/app/profile/notifications'
    | '/app/profile/payment-methods'
    | '/app/profile/refer'
    | '/app/wallet/receive'
    | '/app/wallet/security'
    | '/app/wallet/send'
    | '/onboarding/intro/$step'
    | '/app/market'
    | '/app/profile'
    | '/app/wallet'
    | '/app/market/financing/deposit'
    | '/app/market/financing/eligibility'
    | '/app/market/financing/plan'
    | '/app/market/financing/repay'
    | '/app/market/financing/review'
    | '/app/market/financing/success'
    | '/app/market/invest/$id'
    | '/app/market/invest/amount'
    | '/app/market/invest/confirm'
    | '/app/market/invest/success'
    | '/app/market/product/$id'
    | '/app/wallet/topup/amount'
    | '/app/wallet/topup/method'
    | '/app/wallet/topup/processing'
    | '/app/wallet/topup/success'
    | '/app/wallet/tx/$id'
    | '/app/wallet/withdraw/amount'
    | '/app/wallet/withdraw/method'
    | '/app/wallet/withdraw/success'
    | '/app/wallet/tx'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/admin'
    | '/app/notifications'
    | '/app/offline'
    | '/onboarding/splash'
    | '/onboarding/wallet-creation'
    | '/onboarding/welcome'
    | '/app/'
    | '/app/market/portfolio'
    | '/app/profile/edit'
    | '/app/profile/help'
    | '/app/profile/language'
    | '/app/profile/legal'
    | '/app/profile/logout'
    | '/app/profile/notifications'
    | '/app/profile/payment-methods'
    | '/app/profile/refer'
    | '/app/wallet/receive'
    | '/app/wallet/security'
    | '/app/wallet/send'
    | '/onboarding/intro/$step'
    | '/app/market/'
    | '/app/profile/'
    | '/app/wallet/'
    | '/app/market/financing/deposit'
    | '/app/market/financing/eligibility'
    | '/app/market/financing/plan'
    | '/app/market/financing/repay'
    | '/app/market/financing/review'
    | '/app/market/financing/success'
    | '/app/market/invest/$id'
    | '/app/market/invest/amount'
    | '/app/market/invest/confirm'
    | '/app/market/invest/success'
    | '/app/market/product/$id'
    | '/app/wallet/topup/amount'
    | '/app/wallet/topup/method'
    | '/app/wallet/topup/processing'
    | '/app/wallet/topup/success'
    | '/app/wallet/tx/$id'
    | '/app/wallet/withdraw/amount'
    | '/app/wallet/withdraw/method'
    | '/app/wallet/withdraw/success'
    | '/app/wallet/tx/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offline': {
      id: '/app/offline'
      path: '/offline'
      fullPath: '/app/offline'
      preLoaderRoute: typeof AppOfflineRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/splash': {
      id: '/onboarding/splash'
      path: '/splash'
      fullPath: '/onboarding/splash'
      preLoaderRoute: typeof OnboardingSplashRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/wallet-creation': {
      id: '/onboarding/wallet-creation'
      path: '/wallet-creation'
      fullPath: '/onboarding/wallet-creation'
      preLoaderRoute: typeof OnboardingWalletCreationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/market/': {
      id: '/app/market/'
      path: '/market'
      fullPath: '/app/market/'
      preLoaderRoute: typeof AppMarketIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/portfolio': {
      id: '/app/market/portfolio'
      path: '/market/portfolio'
      fullPath: '/app/market/portfolio'
      preLoaderRoute: typeof AppMarketPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/help': {
      id: '/app/profile/help'
      path: '/profile/help'
      fullPath: '/app/profile/help'
      preLoaderRoute: typeof AppProfileHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/language': {
      id: '/app/profile/language'
      path: '/profile/language'
      fullPath: '/app/profile/language'
      preLoaderRoute: typeof AppProfileLanguageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/legal': {
      id: '/app/profile/legal'
      path: '/profile/legal'
      fullPath: '/app/profile/legal'
      preLoaderRoute: typeof AppProfileLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/logout': {
      id: '/app/profile/logout'
      path: '/profile/logout'
      fullPath: '/app/profile/logout'
      preLoaderRoute: typeof AppProfileLogoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/notifications': {
      id: '/app/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/app/profile/notifications'
      preLoaderRoute: typeof AppProfileNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/payment-methods': {
      id: '/app/profile/payment-methods'
      path: '/profile/payment-methods'
      fullPath: '/app/profile/payment-methods'
      preLoaderRoute: typeof AppProfilePaymentMethodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/refer': {
      id: '/app/profile/refer'
      path: '/profile/refer'
      fullPath: '/app/profile/refer'
      preLoaderRoute: typeof AppProfileReferRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/': {
      id: '/app/wallet/'
      path: '/wallet'
      fullPath: '/app/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/receive': {
      id: '/app/wallet/receive'
      path: '/wallet/receive'
      fullPath: '/app/wallet/receive'
      preLoaderRoute: typeof AppWalletReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/security': {
      id: '/app/wallet/security'
      path: '/wallet/security'
      fullPath: '/app/wallet/security'
      preLoaderRoute: typeof AppWalletSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/send': {
      id: '/app/wallet/send'
      path: '/wallet/send'
      fullPath: '/app/wallet/send'
      preLoaderRoute: typeof AppWalletSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/intro/$step': {
      id: '/onboarding/intro/$step'
      path: '/intro/$step'
      fullPath: '/onboarding/intro/$step'
      preLoaderRoute: typeof OnboardingIntroStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/market/financing/deposit': {
      id: '/app/market/financing/deposit'
      path: '/market/financing/deposit'
      fullPath: '/app/market/financing/deposit'
      preLoaderRoute: typeof AppMarketFinancingDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/financing/eligibility': {
      id: '/app/market/financing/eligibility'
      path: '/market/financing/eligibility'
      fullPath: '/app/market/financing/eligibility'
      preLoaderRoute: typeof AppMarketFinancingEligibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/financing/plan': {
      id: '/app/market/financing/plan'
      path: '/market/financing/plan'
      fullPath: '/app/market/financing/plan'
      preLoaderRoute: typeof AppMarketFinancingPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/financing/repay': {
      id: '/app/market/financing/repay'
      path: '/market/financing/repay'
      fullPath: '/app/market/financing/repay'
      preLoaderRoute: typeof AppMarketFinancingRepayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/financing/review': {
      id: '/app/market/financing/review'
      path: '/market/financing/review'
      fullPath: '/app/market/financing/review'
      preLoaderRoute: typeof AppMarketFinancingReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/financing/success': {
      id: '/app/market/financing/success'
      path: '/market/financing/success'
      fullPath: '/app/market/financing/success'
      preLoaderRoute: typeof AppMarketFinancingSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/invest/$id': {
      id: '/app/market/invest/$id'
      path: '/market/invest/$id'
      fullPath: '/app/market/invest/$id'
      preLoaderRoute: typeof AppMarketInvestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/invest/amount': {
      id: '/app/market/invest/amount'
      path: '/market/invest/amount'
      fullPath: '/app/market/invest/amount'
      preLoaderRoute: typeof AppMarketInvestAmountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/invest/confirm': {
      id: '/app/market/invest/confirm'
      path: '/market/invest/confirm'
      fullPath: '/app/market/invest/confirm'
      preLoaderRoute: typeof AppMarketInvestConfirmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/invest/success': {
      id: '/app/market/invest/success'
      path: '/market/invest/success'
      fullPath: '/app/market/invest/success'
      preLoaderRoute: typeof AppMarketInvestSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market/product/$id': {
      id: '/app/market/product/$id'
      path: '/market/product/$id'
      fullPath: '/app/market/product/$id'
      preLoaderRoute: typeof AppMarketProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/topup/amount': {
      id: '/app/wallet/topup/amount'
      path: '/wallet/topup/amount'
      fullPath: '/app/wallet/topup/amount'
      preLoaderRoute: typeof AppWalletTopupAmountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/topup/method': {
      id: '/app/wallet/topup/method'
      path: '/wallet/topup/method'
      fullPath: '/app/wallet/topup/method'
      preLoaderRoute: typeof AppWalletTopupMethodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/topup/processing': {
      id: '/app/wallet/topup/processing'
      path: '/wallet/topup/processing'
      fullPath: '/app/wallet/topup/processing'
      preLoaderRoute: typeof AppWalletTopupProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/topup/success': {
      id: '/app/wallet/topup/success'
      path: '/wallet/topup/success'
      fullPath: '/app/wallet/topup/success'
      preLoaderRoute: typeof AppWalletTopupSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/tx/': {
      id: '/app/wallet/tx/'
      path: '/wallet/tx'
      fullPath: '/app/wallet/tx/'
      preLoaderRoute: typeof AppWalletTxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/tx/$id': {
      id: '/app/wallet/tx/$id'
      path: '/wallet/tx/$id'
      fullPath: '/app/wallet/tx/$id'
      preLoaderRoute: typeof AppWalletTxIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/withdraw/amount': {
      id: '/app/wallet/withdraw/amount'
      path: '/wallet/withdraw/amount'
      fullPath: '/app/wallet/withdraw/amount'
      preLoaderRoute: typeof AppWalletWithdrawAmountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/withdraw/method': {
      id: '/app/wallet/withdraw/method'
      path: '/wallet/withdraw/method'
      fullPath: '/app/wallet/withdraw/method'
      preLoaderRoute: typeof AppWalletWithdrawMethodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/withdraw/success': {
      id: '/app/wallet/withdraw/success'
      path: '/wallet/withdraw/success'
      fullPath: '/app/wallet/withdraw/success'
      preLoaderRoute: typeof AppWalletWithdrawSuccessRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOfflineRoute: typeof AppOfflineRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMarketPortfolioRoute: typeof AppMarketPortfolioRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileHelpRoute: typeof AppProfileHelpRoute
  AppProfileLanguageRoute: typeof AppProfileLanguageRoute
  AppProfileLegalRoute: typeof AppProfileLegalRoute
  AppProfileLogoutRoute: typeof AppProfileLogoutRoute
  AppProfileNotificationsRoute: typeof AppProfileNotificationsRoute
  AppProfilePaymentMethodsRoute: typeof AppProfilePaymentMethodsRoute
  AppProfileReferRoute: typeof AppProfileReferRoute
  AppWalletReceiveRoute: typeof AppWalletReceiveRoute
  AppWalletSecurityRoute: typeof AppWalletSecurityRoute
  AppWalletSendRoute: typeof AppWalletSendRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppWalletIndexRoute: typeof AppWalletIndexRoute
  AppMarketFinancingDepositRoute: typeof AppMarketFinancingDepositRoute
  AppMarketFinancingEligibilityRoute: typeof AppMarketFinancingEligibilityRoute
  AppMarketFinancingPlanRoute: typeof AppMarketFinancingPlanRoute
  AppMarketFinancingRepayRoute: typeof AppMarketFinancingRepayRoute
  AppMarketFinancingReviewRoute: typeof AppMarketFinancingReviewRoute
  AppMarketFinancingSuccessRoute: typeof AppMarketFinancingSuccessRoute
  AppMarketInvestIdRoute: typeof AppMarketInvestIdRoute
  AppMarketInvestAmountRoute: typeof AppMarketInvestAmountRoute
  AppMarketInvestConfirmRoute: typeof AppMarketInvestConfirmRoute
  AppMarketInvestSuccessRoute: typeof AppMarketInvestSuccessRoute
  AppMarketProductIdRoute: typeof AppMarketProductIdRoute
  AppWalletTopupAmountRoute: typeof AppWalletTopupAmountRoute
  AppWalletTopupMethodRoute: typeof AppWalletTopupMethodRoute
  AppWalletTopupProcessingRoute: typeof AppWalletTopupProcessingRoute
  AppWalletTopupSuccessRoute: typeof AppWalletTopupSuccessRoute
  AppWalletTxIdRoute: typeof AppWalletTxIdRoute
  AppWalletWithdrawAmountRoute: typeof AppWalletWithdrawAmountRoute
  AppWalletWithdrawMethodRoute: typeof AppWalletWithdrawMethodRoute
  AppWalletWithdrawSuccessRoute: typeof AppWalletWithdrawSuccessRoute
  AppWalletTxIndexRoute: typeof AppWalletTxIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOfflineRoute: AppOfflineRoute,
  AppIndexRoute: AppIndexRoute,
  AppMarketPortfolioRoute: AppMarketPortfolioRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileHelpRoute: AppProfileHelpRoute,
  AppProfileLanguageRoute: AppProfileLanguageRoute,
  AppProfileLegalRoute: AppProfileLegalRoute,
  AppProfileLogoutRoute: AppProfileLogoutRoute,
  AppProfileNotificationsRoute: AppProfileNotificationsRoute,
  AppProfilePaymentMethodsRoute: AppProfilePaymentMethodsRoute,
  AppProfileReferRoute: AppProfileReferRoute,
  AppWalletReceiveRoute: AppWalletReceiveRoute,
  AppWalletSecurityRoute: AppWalletSecurityRoute,
  AppWalletSendRoute: AppWalletSendRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppWalletIndexRoute: AppWalletIndexRoute,
  AppMarketFinancingDepositRoute: AppMarketFinancingDepositRoute,
  AppMarketFinancingEligibilityRoute: AppMarketFinancingEligibilityRoute,
  AppMarketFinancingPlanRoute: AppMarketFinancingPlanRoute,
  AppMarketFinancingRepayRoute: AppMarketFinancingRepayRoute,
  AppMarketFinancingReviewRoute: AppMarketFinancingReviewRoute,
  AppMarketFinancingSuccessRoute: AppMarketFinancingSuccessRoute,
  AppMarketInvestIdRoute: AppMarketInvestIdRoute,
  AppMarketInvestAmountRoute: AppMarketInvestAmountRoute,
  AppMarketInvestConfirmRoute: AppMarketInvestConfirmRoute,
  AppMarketInvestSuccessRoute: AppMarketInvestSuccessRoute,
  AppMarketProductIdRoute: AppMarketProductIdRoute,
  AppWalletTopupAmountRoute: AppWalletTopupAmountRoute,
  AppWalletTopupMethodRoute: AppWalletTopupMethodRoute,
  AppWalletTopupProcessingRoute: AppWalletTopupProcessingRoute,
  AppWalletTopupSuccessRoute: AppWalletTopupSuccessRoute,
  AppWalletTxIdRoute: AppWalletTxIdRoute,
  AppWalletWithdrawAmountRoute: AppWalletWithdrawAmountRoute,
  AppWalletWithdrawMethodRoute: AppWalletWithdrawMethodRoute,
  AppWalletWithdrawSuccessRoute: AppWalletWithdrawSuccessRoute,
  AppWalletTxIndexRoute: AppWalletTxIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingSplashRoute: typeof OnboardingSplashRoute
  OnboardingWalletCreationRoute: typeof OnboardingWalletCreationRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIntroStepRoute: typeof OnboardingIntroStepRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingSplashRoute: OnboardingSplashRoute,
  OnboardingWalletCreationRoute: OnboardingWalletCreationRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIntroStepRoute: OnboardingIntroStepRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
